name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    # تغییر از latest به 22.04 برای رفع مشکل نسخه نود جی‌اس
    runs-on: ubuntu-22.04 
    
    # اضافه شدن دسترسی‌های ضروری برای نسخه 4
    permissions:
      contents: read
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: npm install

    - name: Initialize Capacitor
      run: npx cap init "دفتر حساب" "com.studio.invoice" --web-dir=.

    - name: Add Android platform
      run: npx cap add android

    - name: Copy web assets
      run: npx cap copy

    # این خط اضافه شده تا در لینوکس گیت‌هاب، فایل گریدل دسترسی اجرایی داشته باشد
    - name: Make Gradle Executable
      run: chmod +x android/gradlew

    - name: Build APK
      run: cd android && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Invoice-App-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
